services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    restart: unless-stopped
    env_file: ./.env.dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27017:27017
    volumes:
      - dbdata:/usr/src/data/db

  backend:
    build: ./backend
    environment:
      NODE_ENV: development
    image: kanban/backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./.env.dev
      - ./backend/.env.dev
    ports:
      - 4000:4000
      - 9229:9229
    command: "yarn dev"
    depends_on:
      - mongodb

volumes:
  dbdata:
