app:
  build: .
  environment:
    NODE_ENV: development
  env_file:
    - .env.dev
  volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
  ports:
    - 4000:4000
    - 9229:9229
  command: 'yarn dev'
